import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';
import { Navbar } from './components/Navbar';

export const metadata: Metadata = {
  title: 'Rastreamento de veículos - Imersão 14 FC',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <ThemeRegistry>
          <Navbar/>
          {children}
          </ThemeRegistry>
        </body>
    </html>
  )
}
